USE [MED_DATA]
GO

/****** Object:  Table [dbo].[PATIENT_NOTES]    Script Date: 4/10/2024 1:13:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PATIENT_NOTES](
	[PATIENT_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](max) NULL,
	[TRANSCRIPTION] [varchar](max) NULL,
	[KEYWORDS] [varchar](max) NULL,
	[MEDICATIONS] [varchar](max) NULL,
	[ALLERGIES] [varchar](max) NULL,
 CONSTRAINT [PK_PATIENT_NOTES] PRIMARY KEY CLUSTERED 
(
	[PATIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PATIENT_NOTES]  WITH CHECK ADD  CONSTRAINT [FK_PATIENT_NOTES_PATIENT_NOTES] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[PATIENT_NOTES] ([PATIENT_ID])
GO

ALTER TABLE [dbo].[PATIENT_NOTES] CHECK CONSTRAINT [FK_PATIENT_NOTES_PATIENT_NOTES]
GO